import { config } from 'dotenv'

config({ path: '.env' })

export const {
    NODE_ENV,
    HOST,
    PORT,
    CLIENT_PORT,
    CLIENT_URL,
    MONGODB_URI,
    JWT_ACCESS_TOKEN_SECRET_KEY,
    JWT_REFRESH_TOKEN_SECRET_KEY,
    JWT_EMAIL_VERIFY_TOKEN_SECRET_KEY,
    JWT_FORGOT_PASSWORD_TOKEN_SECRET_KEY,
    JWT_ACCESS_TOKEN_EXPIRATION,
    JWT_REFRESH_TOKEN_EXPIRATION,
    JWT_EMAIL_VERIFY_TOKEN_EXPIRATION,
    JWT_FORGOT_PASSWORD_TOKEN_EXPIRATION,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    GOOGLE_REDIRECT_URI,
    CLIENT_REDIRECT_URL,
    AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY,
    AWS_REGION,
    AWS_SENDER_EMAIL,
    AWS_S3_BUCKET_NAME
} = process.env
